### ISSUE TITLE
Plantseg --gui, no buttons to begin the workflow

### ISSUE THREAD

**Issue by Giannisbiol** [kreshuklab/plant-seg#241]
Hi, I just noticed that actually on the latest update, there are no buttons for starting the workflow on the gui (not napari). See image below.

![image](https://github.com/hci-unihd/plant-seg/assets/169128507/d10d129f-96ba-476d-b85f-70d3ed1f88f3)

**Comment by qin-yu** [comment]
What is the PlantSeg version number and your system? I just test the new installation of 1.7.1 on my linux machine:

![image](https://github.com/hci-unihd/plant-seg/assets/17722010/cae78a08-9a1c-490e-a7a8-984fe1c60b7e)

**Comment by Giannisbiol** [comment]
Hi @qin-yu  thank you for your immediate response. The version is the latest. The system is Windows 11.

**Comment by qin-yu** [comment]
I see, but I don't have a Windows machine at the moment. My first guess is that such problem may relate to:

- [High DPI Desktop Application Development on Windows](https://learn.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows)
- [SetProcessDpiAwareness function (shellscalingapi.h)](https://learn.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-setprocessdpiawareness#remarks)

Could you tell me more about your screen resolution?

**Comment by Giannisbiol** [comment]
Its 1920x1200. I had scaling at 125% when I removed it to 100 % they appeared. Thanks!

**Comment by qin-yu** [comment]
Great! My pleasure, thanks for reporting!

**Comment by swethan139** [comment]
Hi!
I have the same issue. I use Windows 11 and my display resolution is 1920*1080 and the scaling factor is 100. How do I go about this issue?

**Comment by qin-yu** [comment]
Hi @swethan139 did you try to make it 1920*1080 with scaling factor is 50% or some other number <100% (so it shows more content)?

**Comment by swethan139** [comment]
The display settings do not allow for the scaling to be less than 100%. I did try other display resolutions. But they didn't work as well!

**Comment by qin-yu** [comment]
Sorry I made the interface too long but I needed to use the parameters. I can fix it but PlantSeg has been moved from Legacy Tk GUI (`--gui`) to Napari interface (`--napari`). If you never used it, try `plantseg --napari` ([here is the docs](https://kreshuklab.github.io/plant-seg/chapters/plantseg_interactive_napari/)). 

The whole idea about finding missing buttons is just to make the window bigger. If there is no way to change the screen and one has to use `--gui`, please try to do this even if the window becomes bigger than the screen itself:

![plantseg-gui](https://github.com/kreshuklab/plant-seg/assets/17722010/af834274-4157-4fcc-bc58-665c3e73b197)

**Comment by qin-yu** [comment]
Hey @lorenzocerrone, for users with small screens (i.e. < `____ x 1200`, 1080 is enough but because of the taskbar some more space is required), not everything is shown in the GUI. Please add a scrollbar or change the layout if it is easy for you; otherwise what I did was:

1. Document that buttons are not missing, just a result of low resolution. 
2. Launch the legacy GUI with fixed `1500 x 1080` size , which can be dragged and changed by users. This doesn't prevent the app to only fill the screen at launch, but once the window is dragged, it becomes `1500 x 1080`. 

Maybe I could just remove the LMC part in "segmentation" because I'm likely to be the only one who ever used it. I already moved to Napari GUI so I don't need it anymore.

**Comment by qin-yu** [comment]
There will be no Legacy mode after PlantSeg V2 release.
