### ISSUE TITLE
Rearrange tabs in napari

### ISSUE THREAD

**Issue by lorenzocerrone** [kreshuklab/plant-seg#246]
Hey @qin-yu, I would like to propose the following changes.

- merge the `predictions` and `segmentation`  in a single `Extra workflows` (to save space for the upcoming training/dataset tab)
- remove the `watershed` in `segmentation` and add back the functionalities in `Main`
- Always use the dropdown menu for `Extra workflow` (i.e., remove the `TOO_MANY_WIDGES = False` check). Having all the widgets open adds a lot of clutter to the UI.

**Comment by qin-yu** [comment]
> * merge the `predictions` and `segmentation`  in a single `Extra workflows` (to save space for the upcoming training/dataset tab)
> * remove the `watershed` in `segmentation` and add back the functionalities in `Main`

These changes doesn't really affect me and might be new-user-friendly.

> * Always use the dropdown menu for `Extra workflow` (i.e., remove the `TOO_MANY_WIDGES = False` check). Having all the widgets open adds a lot of clutter to the UI.

I would like to have easier access to all widgets for more direct feedback ("on_change" events) during development, I propose to have an environment variable to allow this (that's why I did a `TOO_MANY_WIDGES`, but didn't have time to finish)

The workflow for me to segment or to show new users how to segment using PlantSeg is the following:

1. (Add a model)
2. Load an image
3. (Gaussian blur)
4. Run prediction
5. Run watershed
6. Run filter (the one I developed)
7. Run GASP
8. Run filter
9. Export segmentation

So having "Data", "Main", and "Extra" doesn't add complexity for inference. I would say your proposal is nice overall.

**Comment by qin-yu** [comment]
Fixed by #249
