### ISSUE TITLE
Error while trying to open GUI in the latest PlantSeg version

### ISSUE THREAD

**Issue by adkrishnan** [kreshuklab/plant-seg#274]
Hello,
Facing an issue while trying to open the GUI for the latest version of PlantSeg 1.8.1 after an install in a fresh environment
`ModuleNotFoundError: No module named 'bioimage.io'`
(same error even on trying to open Napari GUI)

Even on installing bioimage.core separately
displays an error in the legacy_gui/gui_widgets.py
`KeyError: 'is_segmentation'`

**Comment by qin-yu** [comment]
Hi @adkrishnan thanks for reporting this issue!

Legacy GUI is now not the main focus, but is still very useful. When it launches, it checks this template file and it's configs:
https://github.com/kreshuklab/plant-seg/blob/aece266541317858ba3e793308a752f188302a38/plantseg/resources/config_gui_template.yaml#L84

unless there is already a config file before the installation of PlantSeg in `~/.plantseg_models/configs/` (because you had previous versions of PlantSeg). So if you try to delete the files there, the `KeyError` may be fixed.

**Comment by qin-yu** [comment]
This has been documented before but I know the docs are hard to find when you actually need it:

https://kreshuklab.github.io/plant-seg/chapters/getting_started/troubleshooting/#missing-configuration-key-errors

**Comment by qin-yu** [comment]
Hey @adkrishnan Athul says you tried deleting the folder but still has `KeyError`, in this case I recommend you to try and see what does this give:

```python
(plant-seg) [qyu@kreshuk configs]$ python
Python 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from plantseg import PATH_CONFIGS
>>> PATH_CONFIGS
PosixPath('/home/qyu/.plantseg_models/configs')
```

So basically you need to remove everything inside the `PATH_CONFIGS` to update to the latest config.

**Comment by adkrishnan** [comment]
I deleted everything and installed bioimageio.core using `mamba install -c conda-forge bioimageio.core` separately along with PlantSeg
Its working now
Thankyou very much

**Comment by qin-yu** [comment]
For the missing package it is very strange because I did include it in the config:
https://github.com/kreshuklab/plant-seg/blob/aece266541317858ba3e793308a752f188302a38/conda-recipe/meta.yaml#L34

But since PlantSeg works for you know I'll leave this issue open and come back later to see if anything is wrong with the environment.

Thanks again for reporting!

**Comment by lorenzocerrone** [comment]
I get the same issue on my machine

**Comment by qin-yu** [comment]
> I get the same issue on my machine

Do you know what conda uses for checking the requirements? I have bioimageio.core all three configs:

https://github.com/kreshuklab/plant-seg/blob/aece266541317858ba3e793308a752f188302a38/conda-recipe/meta.yaml#L34

https://github.com/kreshuklab/plant-seg/blob/aece266541317858ba3e793308a752f188302a38/environment-dev.yaml#L27

https://github.com/kreshuklab/plant-seg/blob/aece266541317858ba3e793308a752f188302a38/environment.yaml#L20

**Comment by lorenzocerrone** [comment]
Only `meta.yaml` counts. It is strange that the deps are not built into the package dependencies by Conda, but I have seen it in the past. As a short-term solution, let's add it to the installation instructions.

**Comment by qin-yu** [comment]
> Only `meta.yaml` counts. It is strange that the deps are not built into the package dependencies by Conda, but I have seen it in the past. 

Ohhh I never imagined Conda would do that because it feels like a major bug of it. 

> As a short-term solution, let's add it to the installation instructions.

Do you have time for the docs? Otherwise I can add it after our meeting.
