### ISSUE TITLE
Failed to load or parse config_train.yml: 'loaders'

### ISSUE THREAD

**Issue by Yifan-debug** [kreshuklab/plant-seg#293]
Hi developer, 

I'm trying to train my own data. I checked the tutorial but it is not clear. I followed the tutorial and set the config_train.yml

training:
  dataset_dir: /projectnb/mylabscc/yzw0093/Train_dataset/Plantseg/data/train/images # contains train/val subdirectories
  model_name: custom_model
  in_channels: 1
  out_channels: 2
  feature_maps: [ 32, 64, 128, 256, 512 ]
  patch_size: [ 8, 16, 160 ]
  max_num_iters: 50000
  dimensionality: 3D
  sparse: false
  device: cuda
config_train.yml (END)
Besides. Where should I put my mask file and image file?

Thank you so much

**Comment by qin-yu** [comment]
Hi @Yifan-debug thanks for reporting this! But unfortunately this is not an issue for PlantSeg.

Training will be available in PlantSeg v2 but it's not yet supported. Please use https://github.com/wolny/pytorch-3dunet for training now. If anything is wrong with the config format, it's very likely due to version changes, and you need to see example yaml files in this repo to make changes accordingly.

Dataset should be prepared like this: https://github.com/wolny/pytorch-3dunet?tab=readme-ov-file#input-data-format.
